module.exports = class Data1726492635278 {
    name = 'Data1726492635278'

    async up(db) {
        await db.query(`CREATE TABLE "account_operator" ("id" character varying NOT NULL, "account_id" character varying, "operator_id" character varying, CONSTRAINT "PK_92bb0377f2bb6d9cca67c4bdd69" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_0dd34f8d8c89c684ec794b7667" ON "account_operator" ("account_id") `)
        await db.query(`CREATE INDEX "IDX_d2aaf368f3a47a1c48af728ed4" ON "account_operator" ("operator_id") `)
        await db.query(`CREATE TABLE "operator" ("id" character varying NOT NULL, "operator_id" numeric NOT NULL, "public_key" bytea NOT NULL, "active" boolean NOT NULL, "fee" numeric NOT NULL, "previous_fee" numeric NOT NULL, "whitelisted_contract" bytea NOT NULL, "is_private" boolean NOT NULL, "total_withdrawn" numeric NOT NULL, "last_update_block_number" numeric NOT NULL, "last_update_block_timestamp" numeric NOT NULL, "last_update_transaction_hash" bytea NOT NULL, "validator_count" numeric NOT NULL, "owner_id" character varying, CONSTRAINT "PK_8b950e1572745d9f69be7748ae8" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_0505d3fe39ea8b01c495652191" ON "operator" ("owner_id") `)
        await db.query(`CREATE TABLE "validator_operator" ("id" character varying NOT NULL, "validator_id" character varying, "operator_id" character varying, CONSTRAINT "PK_34ab21ed4075d698a1fabbaaaae" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_3b0ab40773815f9cc4d1f99d05" ON "validator_operator" ("validator_id") `)
        await db.query(`CREATE INDEX "IDX_95ca811cf9b303f4a84bc2ff8d" ON "validator_operator" ("operator_id") `)
        await db.query(`CREATE TABLE "validator" ("id" character varying NOT NULL, "active" boolean NOT NULL, "shares" bytea NOT NULL, "last_update_block_number" numeric NOT NULL, "last_update_block_timestamp" numeric NOT NULL, "last_update_transaction_hash" bytea NOT NULL, "owner_id" character varying, "cluster_id" character varying, CONSTRAINT "PK_ae0a943022c24bd60e7161e0fad" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_f87ff040c4ec9157fad0f0bf9f" ON "validator" ("owner_id") `)
        await db.query(`CREATE INDEX "IDX_e32bdeb6c9b3ce0bbf3f04eeae" ON "validator" ("cluster_id") `)
        await db.query(`CREATE TABLE "account" ("id" character varying NOT NULL, "nonce" numeric NOT NULL, "validator_count" numeric NOT NULL, CONSTRAINT "PK_54115ee388cdb6d86bb4bf5b2ea" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "cluster" ("id" character varying NOT NULL, "operator_ids" integer array NOT NULL, "validator_count" numeric NOT NULL, "network_fee_index" numeric NOT NULL, "index" numeric NOT NULL, "active" boolean NOT NULL, "balance" numeric NOT NULL, "last_update_block_number" numeric NOT NULL, "last_update_block_timestamp" numeric NOT NULL, "last_update_transaction_hash" bytea NOT NULL, "owner_id" character varying, CONSTRAINT "PK_b09d39b9491ce5cb1e8407761fd" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_5c29b46988a3dd2f8ebd715ba4" ON "cluster" ("owner_id") `)
        await db.query(`CREATE TABLE "dao_values" ("id" character varying NOT NULL, "network_fee" numeric NOT NULL, "liquidation_threshold" numeric NOT NULL, "minimum_liquidation_collateral" numeric NOT NULL, "operator_fee_increase_limit" numeric NOT NULL, "declare_operator_fee_period" numeric NOT NULL, "execute_operator_fee_period" numeric NOT NULL, "operator_maximum_fee" numeric NOT NULL, "update_type" character varying(27) NOT NULL, "last_update_block_number" numeric NOT NULL, "last_update_block_timestamp" numeric NOT NULL, "last_update_transaction_hash" bytea NOT NULL, CONSTRAINT "PK_aa6b65a2ea90a481996c2e8b09d" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "cluster_deposited" ("id" character varying NOT NULL, "owner" bytea NOT NULL, "operator_ids" integer array NOT NULL, "value" numeric NOT NULL, "cluster_validator_count" numeric NOT NULL, "cluster_network_fee_index" numeric NOT NULL, "cluster_index" numeric NOT NULL, "cluster_active" boolean NOT NULL, "cluster_balance" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" bytea NOT NULL, CONSTRAINT "PK_d7b86e25fa4ca96c90b3275b738" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "cluster_liquidated" ("id" character varying NOT NULL, "owner" bytea NOT NULL, "operator_ids" integer array NOT NULL, "cluster_validator_count" numeric NOT NULL, "cluster_network_fee_index" numeric NOT NULL, "cluster_index" numeric NOT NULL, "cluster_active" boolean NOT NULL, "cluster_balance" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" bytea NOT NULL, CONSTRAINT "PK_6441833a078b8bd14237d67d3d7" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "cluster_reactivated" ("id" character varying NOT NULL, "owner" bytea NOT NULL, "operator_ids" integer array NOT NULL, "cluster_validator_count" numeric NOT NULL, "cluster_network_fee_index" numeric NOT NULL, "cluster_index" numeric NOT NULL, "cluster_active" boolean NOT NULL, "cluster_balance" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" bytea NOT NULL, CONSTRAINT "PK_cfbb0a78a34e6d1cc3e245d0529" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "cluster_withdrawn" ("id" character varying NOT NULL, "owner" bytea NOT NULL, "operator_ids" integer array NOT NULL, "value" numeric NOT NULL, "cluster_validator_count" numeric NOT NULL, "cluster_network_fee_index" numeric NOT NULL, "cluster_index" numeric NOT NULL, "cluster_active" boolean NOT NULL, "cluster_balance" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" bytea NOT NULL, CONSTRAINT "PK_4e97c3d2581c7f2449287db7423" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "declare_operator_fee_period_updated" ("id" character varying NOT NULL, "value" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" bytea NOT NULL, CONSTRAINT "PK_f7726584e9f34674694ebb60329" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "execute_operator_fee_period_updated" ("id" character varying NOT NULL, "value" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" bytea NOT NULL, CONSTRAINT "PK_321ae946619e38f221c26258afa" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "fee_recipient_address_updated" ("id" character varying NOT NULL, "owner" bytea NOT NULL, "recipient_address" bytea NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" bytea NOT NULL, CONSTRAINT "PK_c3b76e58eeb9884c3b7bfb0629e" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "liquidation_threshold_period_updated" ("id" character varying NOT NULL, "value" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" bytea NOT NULL, CONSTRAINT "PK_ee3b9e1a1e6662fa59801d9a84d" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "minimum_liquidation_collateral_updated" ("id" character varying NOT NULL, "value" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" bytea NOT NULL, CONSTRAINT "PK_b506357fe5253fe9c7cff3efd7e" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "network_earnings_withdrawn" ("id" character varying NOT NULL, "value" numeric NOT NULL, "recipient" bytea NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" bytea NOT NULL, CONSTRAINT "PK_ff90d784c511fdf36da9c1f1592" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "network_fee_updated" ("id" character varying NOT NULL, "old_fee" numeric NOT NULL, "new_fee" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" bytea NOT NULL, CONSTRAINT "PK_47994e27dd5d1def11d2ebc1a64" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "operator_added" ("id" character varying NOT NULL, "operator_id" numeric NOT NULL, "owner" bytea NOT NULL, "public_key" bytea NOT NULL, "fee" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" bytea NOT NULL, CONSTRAINT "PK_d305323536d21524f99eb40b0ce" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "operator_fee_declaration_cancelled" ("id" character varying NOT NULL, "owner" bytea NOT NULL, "operator_id" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" bytea NOT NULL, CONSTRAINT "PK_b5d70a2dc550528902a465699bb" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "operator_fee_declared" ("id" character varying NOT NULL, "owner" bytea NOT NULL, "operator_id" numeric NOT NULL, "block_number" numeric NOT NULL, "fee" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" bytea NOT NULL, CONSTRAINT "PK_9f902fd0f9ab200c8febe2ca971" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "operator_fee_executed" ("id" character varying NOT NULL, "owner" bytea NOT NULL, "operator_id" numeric NOT NULL, "block_number" numeric NOT NULL, "fee" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" bytea NOT NULL, CONSTRAINT "PK_cf4851a10c2cc5b70099e1c3d64" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "operator_fee_increase_limit_updated" ("id" character varying NOT NULL, "value" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" bytea NOT NULL, CONSTRAINT "PK_b1e6c3fbcdefe853c0734af0c67" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "operator_maximum_fee_updated" ("id" character varying NOT NULL, "max_fee" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" bytea NOT NULL, CONSTRAINT "PK_bf93a33be4be9a9c880e991860b" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "operator_removed" ("id" character varying NOT NULL, "operator_id" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" bytea NOT NULL, CONSTRAINT "PK_54fd47f90412f14d41fdeb46410" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "operator_whitelist_updated" ("id" character varying NOT NULL, "operator_id" numeric NOT NULL, "whitelisted" bytea NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" bytea NOT NULL, CONSTRAINT "PK_f40144943ef4ec9e959eabf53a9" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "operator_multiple_whitelist_updated" ("id" character varying NOT NULL, "operator_ids" integer array NOT NULL, "whitelist_addresses" bytea array, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" bytea NOT NULL, CONSTRAINT "PK_bcd80bb516ba2e57e39488b0faa" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "operator_multiple_whitelist_removed" ("id" character varying NOT NULL, "operator_ids" integer array NOT NULL, "whitelist_addresses" bytea array, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" bytea NOT NULL, CONSTRAINT "PK_d826ef82a4267b12ec5825af640" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "operator_whitelisting_contract_updated" ("id" character varying NOT NULL, "operator_ids" integer array NOT NULL, "whitelisting_contract" bytea NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" bytea NOT NULL, CONSTRAINT "PK_d0c418012811d1b146b9e367c2a" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "operator_privacy_status_updated" ("id" character varying NOT NULL, "operator_ids" integer array NOT NULL, "to_private" boolean NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" bytea NOT NULL, CONSTRAINT "PK_96f8aa284b5934dbfb194dc41d2" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "operator_withdrawn" ("id" character varying NOT NULL, "owner" bytea NOT NULL, "operator_id" numeric NOT NULL, "value" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" bytea NOT NULL, CONSTRAINT "PK_77924c5c7c40e72e5ad71dddca8" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "validator_added" ("id" character varying NOT NULL, "owner" bytea NOT NULL, "operator_ids" integer array NOT NULL, "public_key" bytea NOT NULL, "shares" bytea NOT NULL, "cluster_validator_count" numeric NOT NULL, "cluster_network_fee_index" numeric NOT NULL, "cluster_index" numeric NOT NULL, "cluster_active" boolean NOT NULL, "cluster_balance" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" bytea NOT NULL, CONSTRAINT "PK_2a7f7ea53545428c832cddcf2a6" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "validator_removed" ("id" character varying NOT NULL, "owner" bytea NOT NULL, "operator_ids" integer array NOT NULL, "public_key" bytea NOT NULL, "cluster_validator_count" numeric NOT NULL, "cluster_network_fee_index" numeric NOT NULL, "cluster_index" numeric NOT NULL, "cluster_active" boolean NOT NULL, "cluster_balance" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" bytea NOT NULL, CONSTRAINT "PK_567505d2c035b86d7c7ce0e9a7d" PRIMARY KEY ("id"))`)
        await db.query(`ALTER TABLE "account_operator" ADD CONSTRAINT "FK_0dd34f8d8c89c684ec794b76677" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "account_operator" ADD CONSTRAINT "FK_d2aaf368f3a47a1c48af728ed45" FOREIGN KEY ("operator_id") REFERENCES "operator"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "operator" ADD CONSTRAINT "FK_0505d3fe39ea8b01c4956521912" FOREIGN KEY ("owner_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "validator_operator" ADD CONSTRAINT "FK_3b0ab40773815f9cc4d1f99d056" FOREIGN KEY ("validator_id") REFERENCES "validator"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "validator_operator" ADD CONSTRAINT "FK_95ca811cf9b303f4a84bc2ff8d7" FOREIGN KEY ("operator_id") REFERENCES "operator"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "validator" ADD CONSTRAINT "FK_f87ff040c4ec9157fad0f0bf9f3" FOREIGN KEY ("owner_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "validator" ADD CONSTRAINT "FK_e32bdeb6c9b3ce0bbf3f04eeae2" FOREIGN KEY ("cluster_id") REFERENCES "cluster"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "cluster" ADD CONSTRAINT "FK_5c29b46988a3dd2f8ebd715ba49" FOREIGN KEY ("owner_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`DROP TABLE "account_operator"`)
        await db.query(`DROP INDEX "public"."IDX_0dd34f8d8c89c684ec794b7667"`)
        await db.query(`DROP INDEX "public"."IDX_d2aaf368f3a47a1c48af728ed4"`)
        await db.query(`DROP TABLE "operator"`)
        await db.query(`DROP INDEX "public"."IDX_0505d3fe39ea8b01c495652191"`)
        await db.query(`DROP TABLE "validator_operator"`)
        await db.query(`DROP INDEX "public"."IDX_3b0ab40773815f9cc4d1f99d05"`)
        await db.query(`DROP INDEX "public"."IDX_95ca811cf9b303f4a84bc2ff8d"`)
        await db.query(`DROP TABLE "validator"`)
        await db.query(`DROP INDEX "public"."IDX_f87ff040c4ec9157fad0f0bf9f"`)
        await db.query(`DROP INDEX "public"."IDX_e32bdeb6c9b3ce0bbf3f04eeae"`)
        await db.query(`DROP TABLE "account"`)
        await db.query(`DROP TABLE "cluster"`)
        await db.query(`DROP INDEX "public"."IDX_5c29b46988a3dd2f8ebd715ba4"`)
        await db.query(`DROP TABLE "dao_values"`)
        await db.query(`DROP TABLE "cluster_deposited"`)
        await db.query(`DROP TABLE "cluster_liquidated"`)
        await db.query(`DROP TABLE "cluster_reactivated"`)
        await db.query(`DROP TABLE "cluster_withdrawn"`)
        await db.query(`DROP TABLE "declare_operator_fee_period_updated"`)
        await db.query(`DROP TABLE "execute_operator_fee_period_updated"`)
        await db.query(`DROP TABLE "fee_recipient_address_updated"`)
        await db.query(`DROP TABLE "liquidation_threshold_period_updated"`)
        await db.query(`DROP TABLE "minimum_liquidation_collateral_updated"`)
        await db.query(`DROP TABLE "network_earnings_withdrawn"`)
        await db.query(`DROP TABLE "network_fee_updated"`)
        await db.query(`DROP TABLE "operator_added"`)
        await db.query(`DROP TABLE "operator_fee_declaration_cancelled"`)
        await db.query(`DROP TABLE "operator_fee_declared"`)
        await db.query(`DROP TABLE "operator_fee_executed"`)
        await db.query(`DROP TABLE "operator_fee_increase_limit_updated"`)
        await db.query(`DROP TABLE "operator_maximum_fee_updated"`)
        await db.query(`DROP TABLE "operator_removed"`)
        await db.query(`DROP TABLE "operator_whitelist_updated"`)
        await db.query(`DROP TABLE "operator_multiple_whitelist_updated"`)
        await db.query(`DROP TABLE "operator_multiple_whitelist_removed"`)
        await db.query(`DROP TABLE "operator_whitelisting_contract_updated"`)
        await db.query(`DROP TABLE "operator_privacy_status_updated"`)
        await db.query(`DROP TABLE "operator_withdrawn"`)
        await db.query(`DROP TABLE "validator_added"`)
        await db.query(`DROP TABLE "validator_removed"`)
        await db.query(`ALTER TABLE "account_operator" DROP CONSTRAINT "FK_0dd34f8d8c89c684ec794b76677"`)
        await db.query(`ALTER TABLE "account_operator" DROP CONSTRAINT "FK_d2aaf368f3a47a1c48af728ed45"`)
        await db.query(`ALTER TABLE "operator" DROP CONSTRAINT "FK_0505d3fe39ea8b01c4956521912"`)
        await db.query(`ALTER TABLE "validator_operator" DROP CONSTRAINT "FK_3b0ab40773815f9cc4d1f99d056"`)
        await db.query(`ALTER TABLE "validator_operator" DROP CONSTRAINT "FK_95ca811cf9b303f4a84bc2ff8d7"`)
        await db.query(`ALTER TABLE "validator" DROP CONSTRAINT "FK_f87ff040c4ec9157fad0f0bf9f3"`)
        await db.query(`ALTER TABLE "validator" DROP CONSTRAINT "FK_e32bdeb6c9b3ce0bbf3f04eeae2"`)
        await db.query(`ALTER TABLE "cluster" DROP CONSTRAINT "FK_5c29b46988a3dd2f8ebd715ba49"`)
    }
}
